<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <LangVersion>preview</LangVersion>
        <ApplicationIcon>icon.ico</ApplicationIcon>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <PlatformTarget>x64</PlatformTarget>
    </PropertyGroup>

    <ItemGroup>
      <!-- 引用 ASP.NET Core 共享框架 -->
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
  
    <ItemGroup>
      <PackageReference Include="Antlr4.Runtime" Version="4.6.6" />
      <PackageReference Include="AvalonEdit" Version="6.3.0.90" />
      <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
      <PackageReference Include="HandyControl" Version="3.6.0-rc2" />
      <PackageReference Include="linq2db" Version="5.4.1" />
      <PackageReference Include="linq2db.SQLite" Version="5.4.1" />
      <PackageReference Include="Magick.NET-Q16-AnyCPU" Version="14.0.0" />
      <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.22" />
      <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.0.0-1.25277.114">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="4.14.0" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
      <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
      <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
      <PackageReference Include="ModelContextProtocol" Version="0.4.0-preview.3" />
      <PackageReference Include="ModelContextProtocol.AspNetCore" Version="0.4.0-preview.3" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
      <PackageReference Include="NLog" Version="5.3.4" />
      <PackageReference Include="Ookii.Dialogs.WinForms" Version="4.0.0" />
      <PackageReference Include="SemanticVersion" Version="2.1.0" />
      <PackageReference Include="SevenZipExtractor" Version="1.0.19" />
      <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
      <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.4" />
      <PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
      <PackageReference Include="System.Text.Json" Version="8.0.5" />
      <PackageReference Include="Velopack" Version="0.0.869" />
      <PackageReference Include="WPF-UI" Version="3.0.5" />
    </ItemGroup>

    <ItemGroup>
      <Page Update="Views\MainWindow.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Views\Controls\LuaImportItemControl.xaml">
        <Generator>MSBuild:Compile</Generator>
      </Page>
      <Page Update="Views\SubWindows\LuaManagerWindow.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
    </ItemGroup>

    <ItemGroup>
    
      <ProjectReference Include="..\KnowledgeBaseLib\KnowledgeBaseLib.csproj" />
    
      <ProjectReference Include="..\SharedFunctionLib\SharedFunctionLib.csproj" />
    
      <ProjectReference Include="..\UtilCoreLib\UtilCoreLib.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="VERSION" />
      <EmbeddedResource Include="VERSION" />
      <None Remove="lua4.xshd" />
      <EmbeddedResource Include="lua4.xshd" />
      <Compile Remove="data\plugins\RA3MapUtil_LuaImporter\Main.cs" />
      <None Include="data\nano_programs\COPY_TEAM\Main.cs">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Include="data\nano_programs\EXPORT_PLAYERDATA\Main.cs">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Include="data\nano_programs\IMPORT_LUA\Main.cs">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Include="data\nano_programs\IMPORT_LUA_WITH_ACTIVE_CONFIG\Main.cs">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Include="data\nano_programs\IMPORT_PLAYERDATA\Main.cs">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Include="data\nano_programs\NAMED_UNIT_STAT\Main.cs">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Include="data\nano_programs\OPEN_MAP_FOLDER\Main.cs">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Include="data\nano_programs\STAT_TEAM\Main.cs">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Include="data\nano_programs\STAT_TEXTURE\Main.cs">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Include="data\plugins\RA3MapUtil_LuaImporter\Main.cs">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\plugins\RA3MapUtil_LuaImporter\plugin_meta.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\plugins_lib\linq2db.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\plugins_lib\SQLite.Interop.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\plugins_lib\System.Data.SQLite.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\plugins_lib\System.ValueTuple.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\plugins_lib\Readme.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\plugins\RA3MapUtil_LuaImporter\readme.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\plugins_lib\SharedFunctionLib.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\plugins_lib\UtilCoreLib.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\RA3_MapLib_AI_Guide.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <Compile Remove="data\nano_programs\UUID_Generator\Main.cs" />
      <None Include="data\nano_programs\UUID_Generator\Main.cs">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\nano_programs\UUID_Generator\info.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <Compile Remove="data\nano_programs\rect_height\Main.cs" />
      <None Update="data\nano_programs\COR_FORCE_LOOSE_ORE\info.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Include="data\nano_programs\COR_FORCE_LOOSE_ORE\Main.cs">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <Compile Remove="data\nano_programs\COR_FORCE_LOOSE_ORE\Main.cs" />
      <None Include="data\nano_programs\COR_FORCE_LOOSE_ORE\Main.cs" />
      <Compile Remove="data\nano_programs\COPY_TEAM\Main.cs" />
      <None Include="data\nano_programs\COPY_TEAM\Main.cs">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <Compile Remove="data\nano_programs\NAMED_UNIT_STAT\Main.cs" />
      <None Include="data\nano_programs\NAMED_UNIT_STAT\Main.cs">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <Compile Remove="data\nano_programs\STAT_TEXTURE\Main.cs" />
      <None Include="data\nano_programs\STAT_TEXTURE\Main.cs">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <Compile Remove="data\nano_programs\STAT_TEAM\Main.cs" />
      <None Include="data\nano_programs\STAT_TEAM\Main.cs">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\ra3_lua_lib_metadata.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\nano_programs\COPY_TEAM\info.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\nano_programs\NAMED_UNIT_STAT\info.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\nano_programs\STAT_TEAM\info.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\nano_programs\STAT_TEXTURE\info.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\nano_programs\EXPORT_PLAYERDATA\info.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <Compile Remove="data\nano_programs\EXPORT_PLAYERDATA\Main.cs" />
      <None Include="data\nano_programs\EXPORT_PLAYERDATA\Main.cs">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\nano_programs\IMPORT_PLAYERDATA\info.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <Compile Remove="data\nano_programs\IMPORT_PLAYERDATA\Main.cs" />
      <None Include="data\nano_programs\IMPORT_PLAYERDATA\Main.cs">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\nano_programs\EXPORT_SCRIPTDATA\info.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <Compile Remove="data\nano_programs\EXPORT_SCRIPTDATA\Main.cs" />
      <None Include="data\nano_programs\EXPORT_SCRIPTDATA\Main.cs">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\nano_programs\EXPORT_TEAMDATA\info.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <Compile Remove="data\nano_programs\EXPORT_TEAMDATA\Main.cs" />
      <None Include="data\nano_programs\EXPORT_TEAMDATA\Main.cs">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\nano_programs\IMPORT_SCRIPTDATA\info.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <Compile Remove="data\nano_programs\IMPORT_SCRIPTDATA\Main.cs" />
      <None Include="data\nano_programs\IMPORT_SCRIPTDATA\Main.cs">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <Compile Remove="data\nano_programs\IMPORT_TEAMDATA\Main.cs" />
      <None Include="data\nano_programs\IMPORT_TEAMDATA\Main.cs">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\nano_programs\IMPORT_TEAMDATA\info.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\nano_programs\IMPORT_LUA\info.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <Compile Remove="data\nano_programs\IMPORT_LUA\Main.cs" />
      <None Include="data\nano_programs\IMPORT_LUA\Main.cs">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\nano_programs\IMPORT_LUA_WITH_ACTIVE_CONFIG\info.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <Compile Remove="data\nano_programs\IMPORT_LUA_WITH_ACTIVE_CONFIG\Main.cs" />
      <None Include="data\nano_programs\IMPORT_LUA_WITH_ACTIVE_CONFIG\Main.cs">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="data\nano_programs\OPEN_MAP_FOLDER\info.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <Compile Remove="data\nano_programs\OPEN_MAP_FOLDER\Main.cs" />
      <None Include="data\nano_programs\OPEN_MAP_FOLDER\Main.cs">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="data\test\" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="data\imgs\log_viewer_icon.png" />
      <Resource Include="data\imgs\log_viewer_icon.png" />
      <None Remove="data\imgs\coming_soon_icon.png" />
      <Resource Include="data\imgs\coming_soon_icon.png" />
      <None Remove="data\imgs\chat_lua_helper_icon.png" />
      <Resource Include="data\imgs\chat_lua_helper_icon.png" />
      <None Remove="data\imgs\SymmetryTransform_1.png" />
      <Resource Include="data\imgs\SymmetryTransform_1.png" />
      <None Remove="data\imgs\SymmetryTransform_2.png" />
      <Resource Include="data\imgs\SymmetryTransform_2.png" />
      <None Remove="data\imgs\SymmetryTransform_3.png" />
      <Resource Include="data\imgs\SymmetryTransform_3.png" />
      <None Remove="data\imgs\SymmetryTransform_4.png" />
      <Resource Include="data\imgs\SymmetryTransform_4.png" />
      <None Remove="data\imgs\SymmetryTransform_5.png" />
      <Resource Include="data\imgs\SymmetryTransform_5.png" />
      <None Remove="data\imgs\SymmetryTransform_6.png" />
      <Resource Include="data\imgs\SymmetryTransform_6.png" />
      <None Remove="data\imgs\SymmetryTransform_7.png" />
      <Resource Include="data\imgs\SymmetryTransform_7.png" />
      <None Remove="data\imgs\SymmetryTransform_8.png" />
      <Resource Include="data\imgs\SymmetryTransform_8.png" />
      <None Remove="data\imgs\SymmetryTransform_9.png" />
      <Resource Include="data\imgs\SymmetryTransform_9.png" />
      <None Remove="data\imgs\SymmetryTransform_10.png" />
      <Resource Include="data\imgs\SymmetryTransform_10.png" />
      <None Remove="data\imgs\SymmetryTransform_11.png" />
      <Resource Include="data\imgs\SymmetryTransform_11.png" />
      <None Remove="data\imgs\icon.png" />
      <Resource Include="data\imgs\icon.png" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Dreamness.RA3.Map.Facade">
        <HintPath>lib\Dreamness.RA3.Map.Facade.dll</HintPath>
      </Reference>
      <Reference Include="Dreamness.RA3.Map.Lua">
        <HintPath>lib\Dreamness.RA3.Map.Lua.dll</HintPath>
      </Reference>
      <Reference Include="Dreamness.RA3.Map.Parser">
        <HintPath>lib\Dreamness.RA3.Map.Parser.dll</HintPath>
      </Reference>
      <Reference Include="Dreamness.RA3.Map.Transform">
        <HintPath>lib\Dreamness.RA3.Map.Transform.dll</HintPath>
      </Reference>
      <Reference Include="Dreamness.Ra3.Map.Visualization">
        <HintPath>lib\Dreamness.Ra3.Map.Visualization.dll</HintPath>
      </Reference>
      <Reference Include="Dreamness.ScriptExecutor">
        <HintPath>lib\Dreamness.ScriptExecutor.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
